### ISSUE TITLE
500 when browsing to / for a site with only Participation activated

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1046]
If you browse to site.domain.com/participacion it's ok, but if you go to

site.domain.com it gives 500

**Comment by apradillap** [comment]
@furilo , I've been seeing that it doesn't give an error because the Participation Module is activated. One way to fix the error quickly is to remove the modules from the site and first select one of the modules that do have root_path, for example: Gobierto Budgets, Gobierto Indicators, Gobierto People or Gobierto Participation. To solve it correctly, **root_path** should be defined for the modules that currently do not have:
- [ ] Gobierto Development
- [ ] Gobierto Budget Consultations
- [ ] Gobierto CMS

The other modules have:
- Gobierto Budgets: /presupuestos/resumen/2017
- Gobierto Indicators: /indicadores
- Gobierto People: /cargos-y-agendas
- Gobierto Participation: /participacion

**Comment by furilo** [comment]
Let's neutralize this problem with #927
