### ISSUE TITLE
Indicadores / Card format breaks with a long place name

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1133]
<img width="392" alt="imagen" src="https://user-images.githubusercontent.com/24740/32946136-93aada6e-cb96-11e7-99ef-20f87cba0b54.png">

What can we do to fix it?

**Comment by ferblape** [comment]
![screen shot 2017-11-20 at 15 00 40](https://user-images.githubusercontent.com/17616/33021878-99f9b5c4-ce03-11e7-8940-c3806a3b4d48.png)

@furilo confirm this is ok:

- I have reduced the font size to be 0.85em, as in the other cards
- I have increased the width of the text to the 35% instead of the 25%

**Comment by furilo** [comment]
perfect
