### ISSUE TITLE
Allow images as options in polls

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1167]
* An admin can upload an image associated with an answer
* A user can view the image, click to view it bigger in a lightbox, and vote the corresponding option

---- 

- [x] Design
- [ ] Implementation

**Comment by amiedes** [comment]
@furilo I have a few doubts about this issue:

**In the front**

¿How do I put the images here? ¿Just under the text (in small, and then set the lightbox) and then you adjust the sytles if needed?

![captura de pantalla 2018-07-10 a las 9 23 41](https://user-images.githubusercontent.com/9287468/42496041-2a028e98-8425-11e8-89f2-20f7a3f3a538.png)

**In the admin**

I'm not sure how to fit the file input within the modal, because the sandbox does not take into account (or I don't know how to interpret it) that when I place the file input what I get is something like this:

![captura de pantalla 2018-07-10 a las 9 24 49](https://user-images.githubusercontent.com/9287468/42496247-b6a34414-8425-11e8-9284-b98f666f19ea.png)
 
Also, I find a bit confusing that we display the paperclip button next to the edit one. I think the possibility to attach an image should appear once we've already clicked in the edit button.

**Comment by furilo** [comment]
Can you share a video demo of this?

**Comment by amiedes** [comment]
https://www.youtube.com/watch?v=U457GgIkcsg&feature=youtu.be

You can tests in staging here: http://madrid.gobify.net/admin/participation/processes/51/polls/45/edit

I'll need to fix the tests in staging before if we're gonna merge this
