### ISSUE TITLE
Person calendar / Link to previous events?

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#1171]
@amiedes in this screen http://esplugues.gobify.net/agendas/alvaro-ortia, when you select Lista, didn't we had a "previous events" link? I recall discussing its removal for some implementation reason, but I can't recall the exact reason, and don't see any aparent difficulty in providing it, even if we have to lose calendar tab navigation.

**Comment by amiedes** [comment]
@furilo I think it was something like the following:

Both future and past events are rendered in the same `index.html.erb` file, this is **not** done through AJAX. Since the default view is "week view" making the past events list available required one of the following changes:

1. Somehow pass a parameter to the controller when clicking on the "Past events" link, so when the new page gets rendered it knows it has to show the "Past events list view", not the default "week view".
2. Make the events retrieval process through AJAX.

Since the Fullcalendar views already provide a way of navigating backwards, implementing any of these solutions was discarded and the past events link hidden.

**Comment by amiedes** [comment]
You mean we can provide the "past events link" and in that case hide the "month, week, etc." tabs? I think that'd be straightforward to implement.

**Comment by furilo** [comment]
> You mean we can provide the "past events link" and in that case hide the
"month, week, etc." tabs? I think that'd be straightforward to implement.

yes
