### ISSUE TITLE
some help/direction needed for this newbie 

### ISSUE THREAD

**Issue by bishalkc** [PopulateTools/gobierto#1332]
I am trying to install/test gobierto app. Can I please get some direction? I did docker compose up and  I see Rails page when I load the sites.. also I see 5 users in the db but not sure how I can get to login on /admin.
<img width="616" alt="screen shot 2018-01-12 at 5 47 35 pm" src="https://user-images.githubusercontent.com/5494719/34898725-8c14668c-f7c2-11e7-9e7b-e605944ad27c.png">

I am using docker for mac for testing the app.

**Comment by apradillap** [comment]
Dear Bishal:

First of all, thank you for your interest in Gobierto.

We believe that this page appears to you because of one of the latest **browser updates**. A few minutes ago we made a change in Gobierto to fix it. Can you update these changes and try again? From the path where you have the application:

```
git pull # Upgrade to the latest Gobierto version
rake db:reset # Fix local domain
```

After executing these 2 instructions you should be able to access to http://madrid.gobierto.test after start up rails server

We appreciate your understanding as we go this update and I look forward to your answer.

**Comment by bishalkc** [comment]
Thank You Adrián:

I will go through the steps, can you also direct how to use pow in mac/docker for mac? 

I will let you know how this goes shorlty. 

Thanks again

**Comment by apradillap** [comment]
I can't help you on how to use pow in mac/docker, I don't have that configuration, sorry Bishal.

If you run the steps I told you about, you shouldn't have any trouble accessing the application locally.

**Comment by bishalkc** [comment]
Adrián:

Thanks I can see the app now, I added a host entry and its loading. I really appreciate your direction. 

I will have some more newbie question as I try to implement, hope the community wont mind leading me with more directions.

**Comment by apradillap** [comment]
👍  If you have any questions, we will be happy to help you. I close the issue, if you have a doubt open a new issue.
