### ISSUE TITLE
Fallback from Algolia search

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1449]
Algolia account shouldn't be mandatory in the budgets module.

When Algolia is not present, use the ES search implemented in the budgets explorer.

**Comment by amiedes** [comment]
I've done this but I'm not sure if it's exactly what you want:

![captura de pantalla 2018-05-02 a las 17 45 29](https://user-images.githubusercontent.com/9287468/39533950-a72f6f2e-4e30-11e8-8354-4ba759338cab.png)

¿Do you want to keep this styling or adapt the one we use in Algoliasearch results?

¿What is the context of this feature? I don't see the use case for our Gobierto since it's already configured, ¿is it for D**A?

**Comment by ferblape** [comment]
The context is: for some customers that won't use our cloud we don't want to setup Algolia or Amazon S3. So we want to be able to deactivate both features. For the files it's already implemented as a setting in the application.yml. The idea is to have a setting too for the search.

For the moment, the scope of the issue is to replace the search just for budgets module. We will need to decide what to do in the rest of modules. In budgets it's very easy to replace becaue we have this autocomplete.

What you have done looks good to me.

**Comment by furilo** [comment]
> We will need to decide what to do in the rest of modules.

We don't need to worry about this for the time being.
