### ISSUE TITLE
Decouple Gobierto from municipalities

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#1532]
In order to make Gobierto a more generic tool it should be suitable to another kind of entities than municipalities, i.e local entities, universities,...

The main requirement is that the entity has an unique identifier that never overlaps with other identifiers. This identifier will be used in services such as Populate Data to find the data related to this entity.

In the current implementation we are using INE municipalities database, I suggest to replace it with the "Base de datos general de entidades locales", which includes municipalities and many other entities. Apart from the database, Gobierto should allow the admin to introduce an entity not present in the database (she will be forced to introduce an unique ID manually).

This issue is an epic, and the different tasks will be divided in different small and incremental issues.

**Comment by furilo** [comment]
If we are decoupling, maybe we could go even further, and asume more diverse contexts? The extreme (not so extreme really) would be an organization which is not related to any known DB. This would support any kind of organization (a public entity, a university, association, etc). In fact, I would the use the term Organization instead of Entity.

**Comment by furilo** [comment]
Also, in terms of improving the onboarding of any org, another good thing to document is the datastore we are using, and how to load data into it.

**Comment by ferblape** [comment]
This EPIC has been completed
