### ISSUE TITLE
Fix overriding jsGrid default styles 

### ISSUE THREAD

**Issue by Crashillo** [PopulateTools/gobierto#1880]
When a plan is being edited, the table styles displayed by jsGrid are overrided by gobierto forms CSS

#### Related to
#1773 

### Screenshots

<img width="1020" alt="screen shot 2018-09-04 at 18 05 41" src="https://user-images.githubusercontent.com/446459/45043358-3dd39380-b06d-11e8-8d95-f208cf5f48a9.png">
<img width="1107" alt="screen shot 2018-09-04 at 18 05 57" src="https://user-images.githubusercontent.com/446459/45043359-3dd39380-b06d-11e8-94da-27eed1ed36f7.png">
<img width="1057" alt="screen shot 2018-09-04 at 18 02 54" src="https://user-images.githubusercontent.com/446459/45043389-5479ea80-b06d-11e8-9193-a200195c88c6.png">

**Comment by Crashillo** [comment]
I've included the resetting styles, language toggler and default jsgrid styles in the PR #1858

**Comment by furilo** [comment]
@entantoencuanto and @Crashillo this doesn't reach minimun levels of quality/usabilty; you can't consider this ready to Review. Some are consistency issues which you should have spotted/be aware of. 

- [x] Please, can we be consistent and  use our icons, instead of JSGrid defaults? 

![Uploading Captura de pantalla 2018-09-14 a las 9.41.46.png…]()

- [ ] Import and Export links - we have a default place for this secondary actions inside a page. Please stick to it: the admin_tools div you can see in many screens such as https://portalobert.esplugues.cat/presupuestos/resumen/2018. Also, use the icons file-import and file-export for each

- [x] @entantoencuanto: Header row ordering doesn't work for columns in which the content is a select.

- [x] For [PAM](http://esplugues.gobify.net/admin/plans/1/data) meta field is shown in full in normal listing, but the textarea is reduced when editing. The world upside down. Let's show only the first 100 chars of this field on normal view until we decide what to do in a next iteration.

**Comment by Crashillo** [comment]
May we close this issue? Talking offline with @entantoencuanto, he says everything is included in the PR

**Comment by ferblape** [comment]
Pending here:

- [ ] use the icons file-import and file-export for each

**Comment by ferblape** [comment]
Implemented in https://github.com/PopulateTools/gobierto/pull/1858
