### ISSUE TITLE
Fix activity items date in participation home

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#1996]
In http://madrid.gobify.net/participacion, in the "Lo último" section, the displayed date does not correspond to the date where the subject takes place but to the date when the activity item was created.

Problem: not all subject items use the same attribute name. Ej: events use `starts_at` but pages use `published_on`. We have two options:

1. Don't display the date
2. Declare in each model which attribute to show. We already did a similar thing in other projects and it's not difficult.

**Comment by ferblape** [comment]
I prefer the second option, the `ActivityDecorator` should ask for an attribute `public_timestamp` (or similar name).

**Comment by entantoencuanto** [comment]
If we use a `public_timestamp` for the date in last activities boxes, the same criteria should be used in the activities index, otherwise the result can be a little confusing.

![Screen Shot 2018-11-23 at 15.53.46.png](https://images.zenhubusercontent.com/59e88250a468affe6df7489e/77979c69-8e58-4837-8b9e-75cc5bd4876a)

 As an alternative we can display 2 dates:
* The date corresponding to the activity
* The `public_timestamp` date corresponding to the subject, if make sense (maybe a `public_timestamp` for an attachment or contribution doesn't make sense)

**Comment by furilo** [comment]
We have discussed and we'll leave the activity creation date for the moment.
