### ISSUE TITLE
Observatory card update info, not pulled to the right

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#2193]
![Screen Shot 2019-03-27 at 16 51 24](https://user-images.githubusercontent.com/17616/55091171-a0938780-50b0-11e9-97c0-387c30b93679.png)

Looks like the updated date of a card is not being placed to the right. It uses the class `pull-right` but looks like that class has been lost in the CSS.

**Comment by ferblape** [comment]
Also:

1. Align the ? with the text
2. Remove the underline between FB and Twitter icons?
3. It looks like the source name and URL are not displayed now, but the data is in the JSON, investigate why:

![Screen Shot 2019-04-29 at 10 50 13](https://user-images.githubusercontent.com/17616/56885353-90cee080-6a6c-11e9-8bac-f0ade97425bf.png)

**Comment by Crashillo** [comment]
`pull-right` class has been deprecated as of fontAwesome 4.4. It has been replaced by `fa-pull-right`

Further info: https://github.com/FortAwesome/Font-Awesome/issues/12236

**UPDATE**
1 & 2 list-items will be solved then

**Comment by Crashillo** [comment]
Source name wasn't displayed because `json.metadata.indicators` has changed the `key`, from `["source name"]` to `["source_name"]`. Apparently, it doesn't affect anything else, but keep that in mind.
However, two new glitches have came up:
1. Card bars breaks the layout when bars is too long
![imagen](https://user-images.githubusercontent.com/817526/57128213-013e7000-6d93-11e9-8522-9c3aef638218.png)
2. Population Pyramid is throwing a javascript error, so it's not displayed. I'm trying to figure out what's about.

Both errors could be checked at [staging](http://madrid.gobify.net/observatorio)

**Comment by Crashillo** [comment]
Population Pyramid javascript error has been solved, but I think it's a workaround:
`package.json` now includes a **"resolution"** field, in order to force `d3-selection` to use `1.4.0` version. Check the commit:
https://github.com/PopulateTools/gobierto/pull/2273/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Issue is due to yarn dependency resolver brought multiple `d3-selection` version, so it's required to set only one valid version. Check extra info [here](https://github.com/d3/d3-selection/issues/185).

I think it's a workaround, as `d3-selection` may update someday. package.json resolutions field sets a static version.
