### ISSUE TITLE
Person > Declarations > Declaration > Double radio selector 

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#231]
http://madrid.gobierto.dev/admin/people/people/933465536/statements/689271360/edit

![captura de pantalla 2017-01-12 a las 16 05 15](https://cloud.githubusercontent.com/assets/24740/21894852/fbf84308-d8e0-11e6-8dfc-a60433caf1b4.png)

**Comment by danguita** [comment]
@furilo I can't reproduce that with fresh `stable` code. It seems to be caused by missing translations but I've just confirmed those ones are [properly localised](https://github.com/PopulateTools/gobierto/blob/6514b89126594739e4cc3909d394b4677b331e37/config/locales/gobierto_admin/gobierto_people/views/people/person_statements/es.yml#L22-L23). Could you please restart your server and try again?

Let me drop a couple of screenshots from my dev environment:

Spanish locale:

![screen shot 2017-01-12 at 4 11 38 pm](https://cloud.githubusercontent.com/assets/126392/21895177/073137f6-d8e2-11e6-9586-291d8068e3f8.jpg)

Catalan locale:

![screen shot 2017-01-12 at 4 11 49 pm](https://cloud.githubusercontent.com/assets/126392/21895176/072e3bfa-d8e2-11e6-8c9e-568ff2fbf2e7.jpg)
