### ISSUE TITLE
Plans / Plugin: Indicators

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#2344]
This plugin, using https://github.com/PopulateTools/gobierto/issues/2343 will provide a way for users to create Indicator Groups. An admin must: 

- be able to add an indicator group (a table)
- after adding the group, the table will appear and user can edit its contents
- the first column will allow to select an indicator from a vocabulary. 
  - **pending**: 
    - decide how to configure the vocabulary for a given custom field-plugin
    - define an API so an external system can retrieve the Terms list
- the next rows will be date fields
- the front-end component will write to the plugin hidden field after each edit of the user, a json representation of the data

**Comment by amiedes** [comment]
Pending tasks (will add more):

- [x] Bug: vocabulary id is not loaded when other custom field is present, and API request returns 404
- [x] Plugin type sometimes is not visible when editing the custom field
- [x] Not all plugins will use a vocabulary, so update the custom fields form so that the vocabulary selector appears only when relevant
- [x] Translate text "Add" to add a column
- [x] Delete rows button should only appear when a row is selected
- [x] Translate delete rows button text
- [x] Refactor JS code to avoid duplicated code
- [x] Add form field title
- [x] Bug: if we assign the plugin type and the vocabulary in the same request, there's a bug that prevents the vocabulary from being saved (then 404 happens)
- [x] https://rollbar.com/instance/uuid?uuid=0ba83dc3-8a29-477e-a614-bf8831eb5267
- [x] After adding some rows, if form validations fails, information is lost when re-rendering

Pending design adjustments (i'll ping when the rest of the behavior is working properly):

- [ ] Delete rows button
- [ ] Select2

Pending to resolve in this or next issue:

- [ ]  ~rename plugin: plugin structure one plugin per engine~ #2346 
- [ ]  ~decide where to extract the common code~ #2376

**Comment by ferblape** [comment]
![hidefield](https://user-images.githubusercontent.com/17616/59695092-ef514900-91e9-11e9-8e6f-389e9043f5a6.gif)

**Comment by amiedes** [comment]
>  After adding some rows, if form validations fails, information is lost when re-rendering

I haven't been able to reproduce this again and it's working ok now, so I'm marking it as checked.

**Comment by ferblape** [comment]
This can be reviewed in staging. Things to polish in the UI:

- design of the delete rows button, only visibile when a row is selected
- height and width of the table (I think with CSS it'll fit better)
- styles of the `<label>` of the custom field plugin
- select2 interaction, moved to another issue: #2371
