### ISSUE TITLE
Wrong CSS color in plan node

### ISSUE THREAD

**Issue by amiedes** [PopulateTools/gobierto#2653]
In https://portalobert.esplugues.cat/planes/smart-city/2018#2.2.2 => 
Qualitat de vida (Smart Living) + (Smart People) => 
Incrementar l'ús dels canals digitals de comunicació entre la ciutadania i l'Administració => 
APPS

![image](https://user-images.githubusercontent.com/9287468/68105279-4d06d900-fede-11e9-89f5-88548c979978.png)

**Comment by Crashillo** [comment]
That's because is wrong defined at the backoffice (most likely outdated).

Look at [this](https://github.com/PopulateTools/gobierto/blob/master/app/assets/stylesheets/module-planification-custom.scss#L397) for the backoffice reference. You may replace it when you edit a plan https://portalobert.esplugues.cat/admin/plans/8/edit

**Comment by furilo** [comment]
Can you fix it @Crashillo ?

**Comment by Crashillo** [comment]
Esplugues has been updated, both staging and production. I also extended the [reference](https://github.com/PopulateTools/gobierto/blob/master/app/assets/stylesheets/module-planification-custom.scss#L397) I pointed before, for a faster replacement
