### ISSUE TITLE
Document how to create a Gobierto module

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#274]
Complete [the page in the wiki](https://github.com/PopulateTools/gobierto/wiki/How-to-develop-a-new-module-in-Gobierto) or add it to `docs/` folder with the rest of documentation.

**Comment by danguita** [comment]
Hope you don't mind me writing down some words on our special conventions and guidelines. Here is a quick summary:

- We never reach `ActiveRecord::Base` methods directly in Controllers. A *Form* must be implemented in order to abstract these operations, whatever the actual Model implementation is behind the scenes.
- In other words, `ActiveRecord::Base` query methods are not allowed outside the *Model*, *Form* or *Repository*.
- `ActiveRecord::Base` callbacks are only allowed for data integrity.
- The *Form* may be implementing its own callbacks and validations.
- Any dependency we introduce, we wrap it behind a custom API. A *Service* would be a good fit in most cases.
- Think about wrapping any read operations in `ActiveRecord::Base` classes in *Finder* or *Repository* classes so that the actual Model API is completely wrapped behind our custom API.
- ...

**Comment by ferblape** [comment]
Missed this guidelines. Adding them

**Comment by danguita** [comment]
@ferblape Yeah, I should have been added those notes in a new doc 😞 What about staging them as WIP in `docs/development-guidelines.md`?
