### ISSUE TITLE
Data / Index datasets in search

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3034]
When saving a dataset we should index its title and description in the search engine. 

Related: #3007, #3175

**Comment by stbnrivas** [comment]
I see that description if shown without translation

![Screenshot from 2021-04-20 12-04-40](https://user-images.githubusercontent.com/288355/115379036-70f0d400-a1d1-11eb-8fc6-461576785471.png)

and should be like:
![Screenshot from 2021-04-20 12-11-50](https://user-images.githubusercontent.com/288355/115379417-ccbb5d00-a1d1-11eb-8aba-ba129aafb8e9.png)

I need fix first to do searchable according to language. Can I fix in the same PR or should I open new issue?

UPDATE:
description field was not shown because there isn't a transalation... a misunderstanding the label to change language (on top of md with translation) apply to both text areas, and you need to add a text into description textarea


thx

**Comment by stbnrivas** [comment]
After a talk with @ferblape It seems that description (which is a custom field translatable) can not to be added to search.
