### ISSUE TITLE
Contracts Dashboard / Visualizations

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#3465]
https://www.figma.com/proto/gyMSROblmDqjkKt1TT8BcL5G/Gobierto-%2F-Contratos-Subvenciones?node-id=860%3A0&viewport=-703%2C-2961%2C0.5&scaling=min-zoom

These are the visualizations I propose for the Contracts Dashboard: 

1. Treemap: Contract type
2. Beswarm: contract types, number of contracts, volumen of contracts, along time
3. Linechart: Evolution of tenders and contracts, with price differences (we have to check if meaningful data emerges from this)

If time permits: 

4. Treemap of Providers

After we check that data is OK: 

5. Price analysis

**Comment by furilo** [comment]
@ferblape @Crashillo @jorgeatgu  tell me what you think

**Comment by ferblape** [comment]
In the beswarm, if each ball is a contract there'll be a lot of them (i.e in 2019 there are 351.024 tenders), maybe we could group them by ranges of amounts, but I'm not sure if that will work

**Comment by furilo** [comment]
This is for the entity dashboard, so we usually have a reasonable amount of
contracts

**Comment by ferblape** [comment]
🤦 I thought it was also for the comparator...

Ok, another suggestion is to show a single visualization each time instead of all of them with a long scroll, what about adding a visualization selector in the sidebar only visible in the home. Could be:

- Visualize by
  - Tipo de contrato
  - Contratos por tipo, volumen, tamaño, fecha
  - Evolución
  - Tabla resumen
  - ....

**Comment by furilo** [comment]
If we implement it to the comparator, doing ranges may be a solution.

I prefer the long scroll (it's not that long :D) to the risk of users not
selecting different options and not seeing the visualizations...
