### ISSUE TITLE
Force new admins to be associated to a site and a module

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#398]
When a new admin is invited force at least permissions to one site and one module.

**Comment by ferblape** [comment]
Causes this Rollbar: https://rollbar.com/fernando/gobierto/items/315/

**Comment by amaia** [comment]
I've tried to add two new validations to [AdminForm](https://github.com/PopulateTools/gobierto/blob/stable/app/forms/gobierto_admin/admin_form.rb), the one for sites works ok, but the one for site_modules doesn't work because the admin is being [saved in two stages](https://github.com/PopulateTools/gobierto/blob/stable/app/forms/gobierto_admin/admin_form.rb#L98) and `site_modules` returns an [empty array](https://github.com/PopulateTools/gobierto/blob/stable/app/forms/gobierto_admin/admin_form.rb#L47) if the record is not persisted, and the record is only persisted if it's valid, so adding a normal validation breaks it.

Here's what I've tried:

```ruby
validate :at_least_one_site
validate :at_least_one_site_module

def at_least_one_site
  errors.add(:sites, I18n.t('errors.messages.empty')) if sites.empty?
end

def at_least_one_site_module
  errors.add(:site_modules, I18n.t('errors.messages.empty')) if site_modules.empty?
end
```
