### ISSUE TITLE
Calendar > Past days with events should be linked always

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#557]
Now, only if you clicked on "Eventos pasados" does the calendar show past days with events linked. It should link days with past events always.

**Comment by amiedes** [comment]
I found the problem here. The `_calendar_template.html.erb` gets the events to render from a `@events` variable set in `person_events_controller.rb` and which holds the following value:

```ruby
@events = current_site.person_events.upcoming.sorted
```

Using the **_upcoming_** scope prevents past events from being linked from the calendar.

Also, when showing "Eventos pasados", the corresponding controller is `past_person_events_controller.rb`, and `@events` holds the following value:

```
@events = current_site.person_events.past.sorted
```

Using the **_past_** scope now prevents upcoming events from being linked from the calendar.

My question here is:

Apart from linking past events in the calendar, should we also link future events when in the "Eventos Pasados" view? I think it makes sense to always link them, no matter if they are past or upcoming.

Thanks!

**Comment by ferblape** [comment]
Thanks @amiedes. Yes, we should always link all the events in the calendar. Maybe it makes sense to use a different instance variable, independent of the events rendered in the main column.
