### ISSUE TITLE
Amend Sluggable module

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#974]
[Sluggable module](https://github.com/PopulateTools/gobierto/blob/master/app/models/concerns/gobierto_common/sluggable.rb) works fine, but it can be improved a bit:

1. The callback that sets the slug should be `before_validation`. This way, it will work not only after creating but after updating

2. The module should include two validations:
  - validate the presence of the slug
  - validate the uniqueness of the slug in the scope of the site

**Comment by amiedes** [comment]
I have a concern about this concern :trollface:.

If I remember right, the reason why I used `before_create` was because the slug shouldn't be `null` (there is a DB constraint for this). This way, when a user doesn't specify a slug in the interface, it gets auto-assigned when the record is created for the first time.

So, a `before_validation` is not strictly needed, but adding it won't change the current behavior.

**Comment by ferblape** [comment]
After discussing with @amiedes I have updated the issue.

**Comment by apradillap** [comment]
Keep in mind when we do the issue that as it has an after_create, in the case, objects like PersonPost the method attributes_for_slug

```
    def attributes_for_slug
      [created_at. strftime ("%F"), title]
    end
```

It has an attribute that we haven't in the before_validation and we will have to omit the creation_at for the slug no? cc @ferblape

**Comment by ferblape** [comment]
Good point, let's us Time.now.
